configuration:
    link-classes: true
attributes:
    types: []
    typeMapping: []
    properties:
        nullable:      true
        primary-key:   true
        autoincrement: true
        unique:        true
        default:       true
        description:   true
entities:
    types:
        class:     true
        abstract:  true
        interface: true
        trait:     true
    properties:
        programming:
            properties:
              constructor:  true
              repository:   true
              form:         true
              controller:   true
              fixtures:     true
              array-access: true
              crud:         [CRUD, CRU, CUD, CRD, CR, CU, CD, C, RUD, RU, RD, R, UD, U, D]
              to-string:    true
            attribute-properties:
                setter:   true
                getter:   true
                min-size: true
                email:    true
                min:      true
                max:      true
                static:   true
relationships:
    types:
        one-to-one:    true
        one-to-many:   true
        many-to-one:   true
        many-to-many:  true
        inheritance:   true
    properties: ~
autocode:
    properties:
        overwrite:
            name:    Overwrite
            enabled: true
            default: true
        delete-unmapped:
            name:    Delete unmapped
            enabled: true
            default: true
    configurations: []
    templates:      []
languages:  []
frameworks: []
orms:       []