languages:
    java:
        name: Java
    php:
        name: PHP
        entities:
            types:
                trait:
                    name:    Trait
                    enabled: true
        frameworks:
            symfony2:
                name: Symfony 2
                autocode:
                    configurations:
                        namespace:
                            name:    Namespace
                            enabled: true
                    templates:
                        entity:
                            name:     Entity
                            template: Draggy\Autocode\Templates\PHP\Symfony2\Entity1
                            enabled:  true
                        entity-base:
                            name:     Entity base
                            template: Draggy\Autocode\Templates\PHP\Symfony2\EntityBase1
                            enabled:  true
                        interface:
                            name:     Interface
                            template: Draggy\Autocode\Templates\PHP\Symfony2\InterfaceT
                            enabled:  true
                        trait:
                            name:     Trait
                            template: Draggy\Autocode\Templates\PHP\Symfony2\TraitT
                            enabled:  true
                        form:
                            name:     Form
                            template: Draggy\Autocode\Templates\PHP\Symfony2\Form
                            enabled:  true
                        form-base:
                            name:     Form base
                            template: Draggy\Autocode\Templates\PHP\Symfony2\FormBase1
                            enabled:  true
                        crud-create:
                            name:     CRUD (Create)
                            template: Draggy\Autocode\Templates\PHP\Symfony2\CrudCreate
                            enabled:  true
                        crud-read:
                            name:     CRUD (Read / View / List)
                            templace: Draggy\Autocode\Templates\PHP\Symfony2\CrudRead
                            enabled:  true
                        crud-update:
                            name:     CRUD (Update / Edit)
                            template: Draggy\Autocode\Templates\PHP\Symfony2\CrudUpdate
                            enabled:  true
                        controller:
                            name:     Controller
                            template: Draggy\Autocode\Templates\PHP\Symfony2\Controller
                            enabled:  true
                        fixtures:
                            name:     Fixtures
                            template: Draggy\Autocode\Templates\PHP\Symfony2\Fixtures
                            enabled:  true
                        routes:
                            name:     Routes
                            template: Draggy\Autocode\Templates\PHP\Symfony2\Routes
                            enabled:  true
                        routes-routing:
                            name:     Routes (routing)
                            template: Draggy\Autocode\Templates\PHP\Symfony2\RoutesRouting
                            enabled:  true
                        repository:
                            name:     Repository
                            template: Draggy\Autocode\Templates\PHP\Symfony2\Repository
                            enabled:  true
                orms:
                    symfony2-doctrine2:
                        name: Symfony 2 \ Doctrine 2
                        configuration:
                            link-classes: false
                        attributes:
                            types:
                                - array
                                - bigint
                                - boolean
                                - date
                                - datetime
                                - decimal
                                - integer
                                - object
                                - smallint
                                - string
                                - text
                                - time
                            typeMapping:
                                bigint:   integer
                                date:     datetime
                                decimal:  float
                                smallint: integer
                                text:     string
                                time:     datetime
                        relationships:
                            types:
                                many-to-one:  false
                                many-to-many: false
                        autocode:
                            templates:
                                entity:
                                    name:     Entity
                                    template: Draggy\Autocode\Templates\PHP\Symfony2\Doctrine2\Entity1
                                    enabled:  true
                                entity-base:
                                    name:     Entity base
                                    template: Draggy\Autocode\Templates\PHP\Symfony2\Doctrine2\EntityBase1
                                    enabled:  true
                                form:
                                    name:     Form
                                    template: Draggy\Autocode\Templates\PHP\Symfony2\Doctrine2\Form
                                    enabled:  true
                                form-base:
                                    name:     Form base
                                    template: Draggy\Autocode\Templates\PHP\Symfony2\Doctrine2\FormBase1
                                    enabled:  true
                                crud-create:
                                    name:     CRUD (Create)
                                    template: Draggy\Autocode\Templates\PHP\Symfony2\Doctrine2\CrudCreate
                                    enabled:  true
                                crud-read:
                                    name:     CRUD (Read / View / List)
                                    templace: Draggy\Autocode\Templates\PHP\Symfony2\Doctrine2\CrudRead
                                    enabled:  true
                                crud-update:
                                    name:     CRUD (Update / Edit)
                                    template: Draggy\Autocode\Templates\PHP\Symfony2\Doctrine2\CrudUpdate
                                    enabled:  true
                                controller:
                                    name:     Controller
                                    template: Draggy\Autocode\Templates\PHP\Symfony2\Doctrine2\Controller
                                    enabled:  true
                                fixtures:
                                    name:     Fixtures
                                    template: Draggy\Autocode\Templates\PHP\Symfony2\Doctrine2\Fixtures
                                    enabled:  true
                                repository:
                                    name:     Repository
                                    template: Draggy\Autocode\Templates\PHP\Symfony2\Doctrine2\Repository
                                    enabled:  true
        attributes:
            types:
                - array
                - boolean
                - datetime
                - float
                - integer
                - object
                - string
        autocode:
            properties:
                base:
                    name:    Base
                    enabled: true
                    default: true
                validation:
                    name:    Validation
                    enabled: true
                    default: true
            templates:
                entity:
                    name:     Entity
                    template: Draggy\Autocode\Templates\PHP\Entity1
                    enabled:  true
                entity-base:
                    name:     Entity base
                    template: Draggy\Autocode\Templates\PHP\EntityBase1
                    enabled:  true
                interface:
                    name:     Interface
                    template: Draggy\Autocode\Templates\PHP\InterfaceT
                    enabled:  true
                trait:
                    name:     Trait
                    template: Draggy\Autocode\Templates\PHP\TraitT
                    enabled:  true
                form:
                    name:     Form
                    template: Draggy\Autocode\Templates\PHP\Form
                    enabled:  true
                form-base:
                    name:     Form base
                    template: Draggy\Autocode\Templates\PHP\FormBase1
                    enabled:  true
                crud-create:
                    name:     CRUD (Create)
                    template: Draggy\Autocode\Templates\PHP\CrudCreate
                    enabled:  true
                crud-read:
                    name:     CRUD (Read / View / List)
                    templace: Draggy\Autocode\Templates\PHP\CrudRead
                    enabled:  true
                crud-update:
                    name:     CRUD (Update / Edit)
                    template: Draggy\Autocode\Templates\PHP\CrudUpdate
                    enabled:  true
    js:
        name: JavaScript
        attributes:
            types:
                - array
                - boolean
                - number
                - object
                - string
        autocode:
            templates:
                entity:
                    name:     Entity
                    template: Draggy\Autocode\Templates\JS\Entity2
                    enabled:  true
                entity-base:
                    name:     Entity base
                    template: Draggy\Autocode\Templates\JS\EntityBase2
                    enabled:  true
    cpp:
        name: C++