languages:
    java:
        name: Java
        reserved-words: ['abstract', 'continue', 'for', 'new', 'switch', 'assert', 'default', 'goto', 'package', 'synchronized', 'boolean', 'do', 'if', 'private', 'this', 'break', 'double', 'implements', 'protected', 'throw', 'byte', 'else', 'import', 'public', 'throws', 'case', 'enum', 'instanceof', 'return', 'transient', 'catch', 'extends', 'int', 'short', 'try', 'char', 'final', 'interface', 'static', 'void', 'class', 'finally', 'long', 'strictfp', 'volatile', 'const', 'float', 'native', 'super', 'while'] # From: http://docs.oracle.com/javase/tutorial/java/nutsandbolts/_keywords.html
        relationships:
            types:
                one-to-one:
                    enabled: true
                one-to-many:
                    enabled: true
                many-to-one:
                    enabled: true
                many-to-many:
                    enabled: true
                inheritance:
                    enabled: true
        attributes:
            types:
                byte:
                    name:    byte
                    enabled: true
                short:
                    name:    short
                    enabled: true
                int:
                    name:    int
                    enabled: true
                long:
                    name:    long
                    enabled: true
                float:
                    name:    float
                    enabled: true
                double:
                    name:    double
                    enabled: true
                boolean:
                    name:    boolean
                    enabled: true
                char:
                    name:    char
                    enabled: true
                String:
                    name:    String
                    enabled: true
                object:
                    name:    object
                    enabled: true
        autocode:
            properties:
                base:
                    name:    Base
                    enabled: true
                    default: true
            configurations:
                package:
                    name:    Package
                    enabled: true
                    default: sample_package
                target-path:
                    name:    Target path
                    enabled: true
                    default: ~
            templates:
                entity:
                    name:     Entity
                    template: Draggy\Autocode\Templates\Java\Entity
                    type:     entity
                    enabled:  true
                entity-base:
                    name:     Entity base
                    template: Draggy\Autocode\Templates\Java\EntityBase
                    type:     entity
                    enabled:  true
    php:
        name: PHP
        reserved-words: ['__halt_compiler', 'abstract', 'and', 'array', 'as', 'break', 'callable', 'case', 'catch', 'class', 'clone', 'const', 'continue', 'declare', 'default', 'die', 'do', 'echo', 'else', 'elseif', 'empty', 'enddeclare', 'endfor', 'endforeach', 'endif', 'endswitch', 'endwhile', 'eval', 'exit', 'extends', 'final', 'for', 'foreach', 'function', 'global', 'goto', 'if', 'implements', 'include', 'include_once', 'instanceof', 'insteadof', 'interface', 'isset', 'list', 'namespace', 'new', 'or', 'print', 'private', 'protected', 'public', 'require', 'require_once', 'return', 'static', 'switch', 'throw', 'trait', 'try', 'unset', 'use', 'var	while', 'xor', 'yield'] # From: http://www.php.net/manual/en/reserved.keywords.php
        relationships:
            types:
                one-to-one:
                    enabled: true
                one-to-many:
                    enabled: true
                many-to-one:
                    enabled: true
                many-to-many:
                    enabled: true
                inheritance:
                    enabled: true
                implements:
                    enabled: true
                trait:
                    enabled: true
        frameworks:
            symfony2:
                name: Symfony 2
                autocode:
                    configurations:
                        namespace:
                            name:    Namespace
                            enabled: true
                            default: ~
                    templates:
                        entity:
                            name:     Entity
                            template: Draggy\Autocode\Templates\PHP\Symfony2\Entity3
                            type:     entity
                            enabled:  true
                        entity-base:
                            name:     Entity base
                            template: Draggy\Autocode\Templates\PHP\Symfony2\EntityBase3
                            type:     entity
                            enabled:  true
                        controller:
                            name:     Controller
                            template: Draggy\Autocode\Templates\PHP\Symfony2\Controller
                            type:     entity
                            enabled:  true
                        fixtures:
                            name:     Fixtures
                            template: Draggy\Autocode\Templates\PHP\Symfony2\Fixtures
                            type:     entity
                            enabled:  true
                        routes:
                            name:     Routes
                            template: Draggy\Autocode\Templates\PHP\Symfony2\Routes
                            type:     entity
                            enabled:  true
                        routes-routing:
                            name:     Routes (routing)
                            template: Draggy\Autocode\Templates\PHP\Symfony2\RoutesRouting
                            type:     module
                            enabled:  true
                        repository:
                            name:     Repository
                            template: Draggy\Autocode\Templates\PHP\Symfony2\Repository
                            type:     entity
                            enabled:  true
                orms:
                    symfony2-doctrine2:
                        name: Symfony 2 \ Doctrine 2
                        reserved-words: ['ACCESSIBLE', 'ADD', 'ALL', 'ALTER', 'ANALYZE', 'AND', 'AS', 'ASC', 'ASENSITIVE', 'BEFORE', 'BETWEEN', 'BIGINT', 'BINARY', 'BLOB', 'BOTH', 'BY', 'CALL', 'CASCADE', 'CASE', 'CHANGE', 'CHAR', 'CHARACTER', 'CHECK', 'COLLATE', 'COLUMN', 'CONDITION', 'CONSTRAINT', 'CONTINUE', 'CONVERT', 'CREATE', 'CROSS', 'CURRENT_DATE', 'CURRENT_TIME', 'CURRENT_TIMESTAMP', 'CURRENT_USER', 'CURSOR', 'DATABASE', 'DATABASES', 'DAY_HOUR', 'DAY_MICROSECOND', 'DAY_MINUTE', 'DAY_SECOND', 'DEC', 'DECIMAL', 'DECLARE', 'DEFAULT', 'DELAYED', 'DELETE', 'DESC', 'DESCRIBE', 'DETERMINISTIC', 'DISTINCT', 'DISTINCTROW', 'DIV', 'DOUBLE', 'DROP', 'DUAL', 'EACH', 'ELSE', 'ELSEIF', 'ENCLOSED', 'ESCAPED', 'EXISTS', 'EXIT', 'EXPLAIN', 'FETCH', 'FLOAT', 'FLOAT4', 'FLOAT8', 'FOR', 'FORCE', 'FOREIGN', 'FROM', 'FULLTEXT', 'GENERAL', 'GRANT', 'GROUP', 'HAVING', 'HIGH_PRIORITY', 'HOUR_MICROSECOND', 'HOUR_MINUTE', 'HOUR_SECOND', 'IF', 'IGNORE', 'IGNORE_SERVER_IDS', 'IN', 'INDEX', 'INFILE', 'INNER', 'INOUT', 'INSENSITIVE', 'INSERT', 'INT', 'INT1', 'INT2', 'INT3', 'INT4', 'INT8', 'INTEGER', 'INTERVAL', 'INTO', 'IS', 'ITERATE', 'JOIN', 'KEY', 'KEYS', 'KILL', 'LEADING', 'LEAVE', 'LEFT', 'LIKE', 'LIMIT', 'LINEAR', 'LINES', 'LOAD', 'LOCALTIME', 'LOCALTIMESTAMP', 'LOCK', 'LONG', 'LONGBLOB', 'LONGTEXT', 'LOOP', 'LOW_PRIORITY', 'MASTER_HEARTBEAT_PERIOD', 'MASTER_SSL_VERIFY_SERVER_CERT', 'MATCH', 'MAXVALUE', 'MEDIUMBLOB', 'MEDIUMINT', 'MEDIUMTEXT', 'MIDDLEINT', 'MINUTE_MICROSECOND', 'MINUTE_SECOND', 'MOD', 'MODIFIES', 'NATURAL', 'NO_WRITE_TO_BINLOG', 'NOT', 'NULL', 'NUMERIC', 'ON', 'OPTIMIZE', 'OPTION', 'OPTIONALLY', 'OR', 'ORDER', 'OUT', 'OUTER', 'OUTFILE', 'PRECISION', 'PRIMARY', 'PROCEDURE', 'PURGE', 'RANGE', 'READ', 'READ_WRITE', 'READS', 'REAL', /*'REFERENCES',*/ 'REGEXP', 'RELEASE', 'RENAME', 'REPEAT', 'REPLACE', 'REQUIRE', 'RESIGNAL', 'RESTRICT', 'RETURN', 'REVOKE', 'RIGHT', 'RLIKE', 'SCHEMA', 'SCHEMAS', 'SECOND_MICROSECOND', 'SELECT', 'SENSITIVE', 'SEPARATOR', 'SET', 'SHOW', 'SIGNAL', 'SLOW', 'SMALLINT', 'SPATIAL', 'SPECIFIC', 'SQL', 'SQL_BIG_RESULT', 'SQL_CALC_FOUND_ROWS', 'SQL_SMALL_RESULT', 'SQLEXCEPTION', 'SQLSTATE', 'SQLWARNING', 'SSL', 'STARTING', 'STRAIGHT_JOIN', 'TABLE', 'TERMINATED', 'THEN', 'TINYBLOB', 'TINYINT', 'TINYTEXT', 'TO', 'TRAILING', 'TRIGGER', 'UNDO', 'UNION', 'UNIQUE', 'UNLOCK', 'UNSIGNED', 'UPDATE', 'USAGE', 'USE', 'USING', 'UTC_DATE', 'UTC_TIME', 'UTC_TIMESTAMP', 'VALUES', 'VARBINARY', 'VARCHAR', 'VARCHARACTER', 'VARYING', 'WHEN', 'WHERE', 'WHILE', 'WITH', 'WRITE', 'XOR', 'YEAR_MONTH', 'ZEROFILL', 'FALSE', 'TRUE'] # // MySQL 5.5 reserved words as per http://dev.mysql.com/doc/refman/5.5/en/reserved-words.html
                        configuration:
                            link-classes: false
                        attributes:
                            types:
                                bigint:
                                    name:      bigint
                                    enabled:   true
                                    mapped-to: integer
                                date:
                                    name:      date
                                    enabled:   true
                                    mapped-to: object
                                decimal:
                                    name:       decimal
                                    enabled:    true
                                    mapped-to:  float
                                smallint:
                                    name:      smallint
                                    enabled:   true
                                    mapped-to: integer
                                text:
                                    name:      text
                                    enabled:   true
                                    mapped-to: string
                                time:
                                    name:      time
                                    enabled:   true
                                    mapped-to: object
                        relationships:
                            types:
                                one-to-one:
                                    connect-entity: false
                                one-to-many:
                                    connect-entity: false
                                many-to-one:
                                    enabled: false
                                many-to-many:
                                    enabled: false
                        autocode:
                            templates:
                                entity:
                                    name:     Entity
                                    template: Draggy\Autocode\Templates\PHP\Symfony2\Doctrine2\Entity4
                                    type:     entity
                                    enabled:  true
                                entity-base:
                                    name:     Entity base
                                    template: Draggy\Autocode\Templates\PHP\Symfony2\Doctrine2\EntityBase4
                                    type:     entity
                                    enabled:  true
        attributes:
            types:
                array:
                    name:    array
                    enabled: true
                boolean:
                    name:    boolean
                    enabled: true
                datetime:
                    name:    datetime
                    enabled: true
                float:
                    name:    float
                    enabled: true
                integer:
                    name:    integer
                    enabled: true
                object:
                    name:    object
                    enabled: true
                string:
                    name:    string
                    enabled: true
        autocode:
            properties:
                base:
                    name:    Base
                    enabled: true
                    default: true
                validation:
                    name:    Validation
                    enabled: true
                    default: true
            templates:
                entity:
                    name:     Entity
                    template: Draggy\Autocode\Templates\PHP\Entity1
                    type:     entity
                    enabled:  true
                entity-base:
                    name:     Entity base
                    template: Draggy\Autocode\Templates\PHP\EntityBase1
                    type:     entity
                    enabled:  true
                interface:
                    name:     Interface
                    template: Draggy\Autocode\Templates\PHP\InterfaceT
                    type:     entity
                    enabled:  true
                trait:
                    name:     Trait
                    template: Draggy\Autocode\Templates\PHP\TraitT
                    type:     entity
                    enabled:  true
                form:
                    name:     Form
                    template: Draggy\Autocode\Templates\PHP\Form
                    type:     entity
                    enabled:  true
                form-base:
                    name:     Form base
                    template: Draggy\Autocode\Templates\PHP\FormBase1
                    type:     entity
                    enabled:  true
                crud-create:
                    name:     CRUD (Create)
                    template: Draggy\Autocode\Templates\PHP\CrudCreate
                    type:     entity
                    enabled:  true
                crud-read:
                    name:     CRUD (Read / View / List)
                    template: Draggy\Autocode\Templates\PHP\CrudRead
                    type:     entity
                    enabled:  true
                crud-update:
                    name:     CRUD (Update / Edit)
                    template: Draggy\Autocode\Templates\PHP\CrudUpdate
                    type:     entity
                    enabled:  true
    js:
        name: JavaScript
        attributes:
            types:
                - array
                - boolean
                - number
                - object
                - string
        autocode:
            templates:
                entity:
                    name:     Entity
                    template: Draggy\Autocode\Templates\JS\Entity2
                    type:     entity
                    enabled:  true
                entity-base:
                    name:     Entity base
                    template: Draggy\Autocode\Templates\JS\EntityBase2
                    type:     entity
                    enabled:  true
    cpp:
        name: C++