# Project routes
draggy_model:
    pattern:  /{file}
    defaults:
        _controller: DraggyBundle:Default:draggy
        file: null

draggy_generate:
    pattern:  /generate/{file}
    defaults:
        _controller: DraggyBundle:Default:generate
        file: null

draggy_preview:
    pattern:  /preview/{file}
    defaults:
        _controller: DraggyBundle:Default:preview
        file: null

draggy_save:
    pattern:  /save/{file}
    defaults:
        _controller: DraggyBundle:Default:save
        file: null
    requirements:
        _method:  POST

# Self project, autocode routes
self_autocode_model:
    pattern: /_self/autocode
    defaults:
        _controller: DraggyBundle:Default:draggy
        file: 'autocode.xml'
        self: true

self_autocode_generate:
    pattern: /_self/generate/autocode
    defaults:
        _controller: DraggyBundle:Default:generate
        file: 'autocode.xml'
        self: true

self_autocode_preview:
    pattern: /_self/preview/autocode
    defaults:
        _controller: DraggyBundle:Default:preview
        file: 'autocode.xml'
        self: true

self_autocode_save:
    pattern: /_self/save/autocode
    defaults:
        _controller: DraggyBundle:Default:save
        file: 'autocode.xml'
        self: true