# Project routes
draggy_model:
    pattern:  /
    defaults: { _controller: DraggyBundle:Default:draggy }

draggy_generate:
    pattern:  /generate
    defaults: { _controller: DraggyBundle:Default:generate }

draggy_preview:
    pattern:  /preview
    defaults: { _controller: DraggyBundle:Default:preview }

draggy_save:
    pattern:  /save
    defaults: { _controller: DraggyBundle:Default:save }
    requirements:
        _method:  POST

# Self project, autocode routes
self_autocode_model:
    pattern: /_self/autocode
    defaults:
        _controller: DraggyBundle:Default:draggy
        file: 'autocode.xml'
        self: true

self_autocode_generate:
    pattern: /_self/generate/autocode
    defaults:
        _controller: DraggyBundle:Default:generate
        file: 'autocode.xml'
        self: true

self_autocode_preview:
    pattern: /_self/preview/autocode
    defaults:
        _controller: DraggyBundle:Default:preview
        self: true

self_autocode_save:
    pattern: /_self/save/autocode
    defaults:
        _controller: DraggyBundle:Default:save
        self: true